site_name: metablate

theme:
  name: "material"
  logo: assets/ablate.png
  favicon: assets/ablate_fav.png
  features:
    - navigation.instant
    - navigation.path
    - navigation.top
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: "#002d72"
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: "#002d72"
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
  icon:
    repo: fontawesome/brands/github


repo_url: https://github.com/danielk333/ablate

extra_css:
  - assets/style.css

markdown_extensions:
  - footnotes
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - search
  - section-index
  - gen-files:
      scripts:
        - scripts/generate_api_docs.py
  - literate-nav:
      nav_file: nav.md
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: numpy
            docstring_section_style: table
            show_docstring_functions: true
            show_docstring_modules: true
            show_docstring_description: true
  - mkdocs-jupyter:
      execute: true
      include_source: True
      include: ["*.py", "*.ipynb"]
      ignore: ["_wip*"]
      # ignore: ["*"]
      theme: dark

nav:
  - Home: index.md
  - Getting started: getting_started.md
  - Examples:
    - examples/index.md
    - alpha_beta: examples/alpha_beta.py
    - alpha_beta_partial_data: examples/alpha_beta_partial_data.py
    - calculate_gamma_lambda: examples/calculate_gamma_lambda.py
    - compare_alpha_beta_num_ablation: examples/compare_alpha_beta_num_ablation.py
    - compare_sputtering: examples/compare_sputtering.py
    - drag_versus_size: examples/drag_versus_size.py
    - example_ablation_model_run: examples/example_ablation_model_run.py
    - fit_alpha_beta: examples/fit_alpha_beta.py
    - heat_coef_versus_size: examples/heat_coef_versus_size.py
    - height_rescaling: examples/height_rescaling.py
    - plot_msise00: examples/plot_msise00.py
    - plot_pymsis: examples/plot_pymsis.py
  - Notebooks:
    - notebooks/index.md
  - Reference: reference/
